import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Header } from "@/components/header";
import QueryProvider from "@/components/QueryProvider";

import "./styles/globals.scss";

const poppins = Poppins({

  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={poppins.className} suppressHydrationWarning>
      <body>
        <>
        <QueryProvider>
           <Header />
          {children}
        </QueryProvider>

        </>

      </body>
    </html>
  );
}
